# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Katerina Brani
email: katerina.brani@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Katerina Brani - Graphic & Product Designer: Online porfolio.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://katerinabrani.me" # the base hostname & protocol for your site

github_username:  KaterinaBr
linkedin_username: katerinabrani

# Build settings
markdown: kramdown

collections:
  projects:
    output: true
    permalink: /portfolio/:path/
